# InfiniteJump configuration
# by MrMicky

UpdateChecker: false

#Cooldown between each jump in ticks
Cooldown: 5

Velocity: 1.5
VelcocityUp: 2

Sound:
  Enable: false
  Sound: ENTITY_BAT_TAKEOFF
  Volume: 1.0
  Pitch: 1.0

Particles:
  Enable: false
  Particle: CRIT_MAGIC
  Amount: 5

Messages:
  Activated: "&aDouble jump włączony"
  Disabled: "&cDouble jump wyłączony"

RemoveFallDamages: true

EnableOnJoin: true

WorldsWhitelist: true

Worlds:
- "mashroomknock"

