name: MushroomKnock-BlazePvP
version: ${project.version}
author: Us + Github guy
description: The ultimate double jump plugin !
website: https://www.spigotmc.org/resources/inifinitejump.51522/
softdepend: [Spartan, AAC, NoCheatPlus]
main: fr.mrmicky.infinitejump.InfiniteJump
api-version: 1.8
commands: 
  infinitejump:
    description: Toggle infinite jump or reload the config
    aliases: [ijump]
    usage: /<command> [toggle|reload]
